# docker-compose.neo4j.yml
version: "3.8"
services:
  neo4j:
    image: neo4j:5.22.0
    container_name: neo4j
    ports:
      - "7474:7474"   # Browser
      - "7687:7687"   # Bolt
    environment:
      NEO4J_AUTH: neo4j/neo4jpass
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
    volumes:
      - ./import:/var/lib/neo4j/import
      - neo4j-data:/data
volumes:
  neo4j-data:
